# Generated by Django 5.2.1 on 2025-06-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_categoria_login_produto_categoriaproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='CEP',
            field=models.CharField(default='00000-000', max_length=9),
        ),
        migrations.AddField(
            model_name='usuario',
            name='bairro',
            field=models.CharField(default='Não informado', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(default='XX', max_length=2),
        ),
        migrations.AddField(
            model_name='usuario',
            name='localidade',
            field=models.CharField(default='Não informado', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='logradouro',
            field=models.CharField(default='Não informado', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_residencia',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=100),
        ),
    ]
