# Generated by Django 5.2.1 on 2025-06-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usuario_cep_usuario_bairro_usuario_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='CEP',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='localidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='logradouro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_residencia',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
