# Generated by Django 5.2.1 on 2025-06-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_usuario_cep_alter_usuario_bairro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='CEP',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='bairro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='localidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='logradouro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_residencia',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=16),
        ),
    ]
