# Generated by Django 5.2.1 on 2025-06-05 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_usuario_cep_alter_usuario_bairro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_cartao', models.CharField(max_length=200)),
                ('validade', models.CharField(max_length=200)),
                ('cvv', models.CharField(max_length=200)),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.usuario')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.produto')),
            ],
        ),
    ]
