# Generated by Django 5.2.1 on 2025-06-06 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='produto',
        ),
        migrations.AddField(
            model_name='venda',
            name='imagem_url',
            field=models.URLField(default='https://via.placeholder.com/150'),
        ),
        migrations.AddField(
            model_name='venda',
            name='nome_produto',
            field=models.CharField(default='Produto removido', max_length=255),
        ),
        migrations.AddField(
            model_name='venda',
            name='produto_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cvv',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='venda',
            name='numero_cartao',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='venda',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venda',
            name='validade',
            field=models.CharField(max_length=7),
        ),
    ]
