# Generated by Django 5.2.2 on 2025-06-06 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_venda_produto_venda_imagem_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='imagem_url',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='nome_produto',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='produto_id',
        ),
        migrations.AddField(
            model_name='venda',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.produto'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.usuario'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cvv',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='venda',
            name='numero_cartao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='venda',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venda',
            name='validade',
            field=models.CharField(max_length=200),
        ),
    ]
